### ISSUE TITLE
Erroneous and missing measurements despite correct DNA segmentation

### ISSUE THREAD

**Issue by TobiasKletter** [tischi/spindle3d#5]
This problem occurred many times in a data set that was working fine with the previous version. So far, this is the only dataset with this issue:

The outputs all have a similar pattern:
![image](https://user-images.githubusercontent.com/45814595/90520911-37f7ef80-e16a-11ea-8d99-b023a1c61f1c.png)

Visually, the DNA segmentation worked correctly. However, the downstream analysis in the tubulin channel is not working. Interestingly, the DNA Volume in the output table is much too high, more than 10x the value I would expect, yet this is also happening in cases where the downstream analysis is working fine!

https://www.dropbox.com/s/qc9da4rmdpr339u/20200605_HeLa_MCB309_024-1.tif?dl=0
https://www.dropbox.com/s/cg9pa70jtg2lqpp/20200605_HeLa_MCB309_025-1.tif?dl=0
https://www.dropbox.com/s/igpixks34x4r5pw/20200605_HeLa_MCB309_026-1.tif?dl=0

**Comment by tischi** [comment]
@TobiasKletter 
I think I found the reason: these images are rather tight in a sense that there is not much empty space around the DNA. Now, if I align the images along the DNA axis I rotate them such that the DNA axis is along the z-axis of the aligned image. This rotation created empty pixels (of value zero) in the aligned image because of above mentioned missing empty space. And thus the automated Otsu thresholding did not work because it got confused by the many pixels of value zero. 
I think fixed this by extending the images with the value of the border pixel (rather than zero) during the rotation.

1. Could you confirm that the "Otsu threshold" gave much too low values in these images? You can see it in the log window.
2. Could you update your Fiji and check whether it works now better?

**Comment by TobiasKletter** [comment]
@tischi 
After updating, the analysis looks good, judging by the intermediate output images. However, the measurements are not saved and I again get this error (also posted in #6 ):
```
## Spindle Morphometry Measurement
Processing file 20200605_HeLa_MCB309_025-1.tif
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Create isotropic images...
DNA initial threshold: 901.5
Remove small regions...
Determining DNA axes...
Creating aligned images...
Measuring DNA axial extend...
DNA axial profile threshold 0: 1137.4182913860334
DNA axial profile threshold 1: 1005.885501595179
Measuring DNA lateral extend...
DNA lateral profile threshold 1346.968085106383
DNA Otsu threshold: 1048.0
Remove small regions...
Spindle threshold: 1255.9350539787752
Computing mask...
Spindle max derivative plus offset -7.0
Spindle max derivative minus offset 7.0
[DEBUG] Spindle_length: 14.0
[DEBUG] Refined Spindle_length: 13.329947486768281
Computing mask...
Creating projection of spindle mask along spindle axis...
Version: Spindle Morphometry Version: 0.7.0
DNA_Initial_Threshold: 901.5
DNA_Volume_Threshold: 1048.0
DNA_Width_um: 3.25
DNA_Length_um: 15.0
DNA_Volume_um3: 560.8125
DNA_Normalised_Central_Intensity: 0.7283233843050673
Spindle_Pole_Refinement_Distance_PoleA_um: 1.4361406616345072
Spindle_Pole_Refinement_Distance_PoleB_um: 0.6123724356957945
Spindle_Length_um: 13.329947486768281
Spindle_Intensity_Threshold: 1255.9350539787752
Spindle_Volume_um3: 685.65625
Spindle_Width_Min_um: 9.5
Spindle_Width_Max_um: 11.75
Dna_Center_To_Spindle_Center_Distance_um: 0.739509972887452
Spindle_Axis_To_Coverslip_Plane_Angle_Degrees: 2.3824778536843496
Spindle_Tubulin_CoV: 0.9289248920877372
Spindle_Tubulin_Sum: 1.882117896130339E7
Analysis finished.
[ERROR] Module threw error
java.lang.NoSuchMethodError: de.embl.cba.morphometry.Utils.asRoundedLongs([D)[J
	at de.embl.cba.spindle3d.Spindle3DMorphometry.drawPoint(Spindle3DMorphometry.java:1665)
	at de.embl.cba.spindle3d.Spindle3DMorphometry.createInterestPointImage(Spindle3DMorphometry.java:1440)
	at de.embl.cba.spindle3d.Spindle3DMorphometry.createOutputImage(Spindle3DMorphometry.java:1524)
	at de.embl.cba.spindle3d.Spindle3DAdvancedCommand.processFile(Spindle3DAdvancedCommand.java:171)
	at de.embl.cba.spindle3d.Spindle3DAdvancedCommand.run(Spindle3DAdvancedCommand.java:107)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748) 
```

**Comment by TobiasKletter** [comment]
Solved!

**Comment by TobiasKletter** [comment]
Hi @tischi 
In rare cases, the issue seems to live on, or is this something different?
![image](https://user-images.githubusercontent.com/45814595/93188144-ecbd0680-f740-11ea-89c7-b0e921a7f375.png)
https://www.dropbox.com/s/hrlh42h3uojvkhl/20200826_HeLa309_TubGFP_Hoechst__PFAGA_YesMounting_005-1.tif?dl=0

![image](https://user-images.githubusercontent.com/45814595/93189070-090d7300-f742-11ea-8488-c0e23cacf624.png)
https://www.dropbox.com/s/bwi2kj0fxasqyj7/20200826_R1E309_TubGFP_Hoechst_CDK5RAP2_PFAGA_NoMounting_001-2.tif?dl=0

```
## Spindle Morphometry Settings
workingVoxelSize: 0.25
dnaThresholdResolution: 1.5
dnaThresholdFactor: 0.5
spindleDerivativeDelta: 1.0
minimalDynamicRange: 7
minimalDnaFragmentsVolume: 5.0
maxCentralObjectRegionsDistance: 7.0
erosionOfDnaMaskInCalibratedUnits: 1.0

## Spindle Morphometry Measurement
Processing file 20200826_R1E309_TubGFP_Hoechst_CDK5RAP2_PFAGA_NoMounting_001-2.tif
Create isotropic images...
DNA initial threshold: 3863.0
Remove small regions...
Determining DNA axes...
Creating aligned images...
Measuring DNA axial extend...
DNA axial profile threshold 0: 3104.1431724137933
DNA axial profile threshold 1: 3142.1875862068964
Measuring DNA lateral extend...
DNA lateral profile threshold 5862.486842105263
DNA Otsu threshold: 3688.0
Remove small regions...
Spindle threshold: NaN
Computing mask...
Computing mask...
Creating projection of spindle mask along spindle axis...
Version: Spindle Morphometry Version: 0.7.0
DNA_Initial_Threshold: 3863.0
DNA_Volume_Threshold: 3688.0
DNA_Width_um: 3.5
DNA_Length_um: 12.0
DNA_Volume_um3: 509.4375
DNA_Normalised_Central_Intensity: 0.9609334009638596
Spindle_Pole_Refinement_Distance_PoleA_um: 2.704163456597992
Spindle_Pole_Refinement_Distance_PoleB_um: 1.9685019685029528
Spindle_Length_um: 15.035374953754895
Spindle_Intensity_Threshold: NaN
Spindle_Volume_um3: 0.0
Spindle_Width_Min_um: 0.0
Spindle_Width_Max_um: 0.0
Dna_Center_To_Spindle_Center_Distance_um: 8.311325104939645
Spindle_Axis_To_Coverslip_Plane_Angle_Degrees: 23.23155764356983
Spindle_Tubulin_CoV: NaN
Spindle_Tubulin_Sum: NaN
Analysis finished.
```

**Comment by tischi** [comment]
For me it works.
At least in one of them the channel order was different (maybe that's the reason?):

```
		command.spindleChannelIndexOneBased = 2;  // normally 1
		command.dnaChannelIndexOneBased = 1; // normally 2
```

**Comment by TobiasKletter** [comment]
Hi @tischi 
I'm still getting the same outputs 🤷‍♂️ 
Channel assignments were correct (1 = DNA, 2 = spindle)

```
## Spindle Morphometry Settings
workingVoxelSize: 0.25
dnaThresholdResolution: 1.5
dnaThresholdFactor: 0.5
spindleDerivativeDelta: 1.0
minimalDynamicRange: 8
minimalDnaFragmentsVolume: 5.0
maxCentralObjectRegionsDistance: 7.0
erosionOfDnaMaskInCalibratedUnits: 1.0
 
## Spindle Morphometry Measurement
Processing file 20200826_HeLa309_TubGFP_Hoechst__PFAGA_YesMounting_005-1.tif
Create isotropic images...
DNA downscaled minimum value: 600.0
DNA downscaled maximum value: 30955.0
DNA initial threshold factor: 0.5
DNA initial threshold (max-min)*factor + min: 15777.5
Remove small regions...
Determining DNA axes...
Creating aligned images...
Measuring DNA axial extend...
DNA axial profile threshold 0: 11248.89719957462
DNA axial profile threshold 1: 11613.853243530662
Measuring DNA lateral extend...
DNA lateral profile threshold 17559.298780487807
DNA Otsu threshold: 13148.0
Remove small regions...
Spindle threshold: NaN
Computing mask...
Computing mask...
Creating projection of spindle mask along spindle axis...
Version: Spindle Morphometry Version: 0.7.1
DNA_Initial_Threshold: 15777.5
DNA_Volume_Threshold: 13148.0
DNA_Width_um: 3.5
DNA_Length_um: 13.5
DNA_Volume_um3: 501.25
DNA_Normalised_Central_Intensity: 0.91155746465598
Spindle_Pole_Refinement_Distance_PoleA_um: 2.0766559657295187
Spindle_Pole_Refinement_Distance_PoleB_um: 0.75
Spindle_Length_um: 13.329947486768281
Spindle_Intensity_Threshold: NaN
Spindle_Volume_um3: 0.0
Spindle_Width_Min_um: 0.0
Spindle_Width_Max_um: 0.0
Dna_Center_To_Spindle_Center_Distance_um: 7.24029522878729
Spindle_Axis_To_Coverslip_Plane_Angle_Degrees: 17.951140878882498
Spindle_Tubulin_CoV: NaN
Spindle_Tubulin_Sum: NaN
Analysis finished.


## Spindle Morphometry Settings
workingVoxelSize: 0.25
dnaThresholdResolution: 1.5
dnaThresholdFactor: 0.5
spindleDerivativeDelta: 1.0
minimalDynamicRange: 8
minimalDnaFragmentsVolume: 5.0
maxCentralObjectRegionsDistance: 7.0
erosionOfDnaMaskInCalibratedUnits: 1.0
 
## Spindle Morphometry Measurement
Processing file 20200826_R1E309_TubGFP_Hoechst_CDK5RAP2_PFAGA_NoMounting_001-2.tif
Create isotropic images...
DNA downscaled minimum value: 626.0
DNA downscaled maximum value: 7726.0
DNA initial threshold factor: 0.5
DNA initial threshold (max-min)*factor + min: 4176.0
Remove small regions...
Determining DNA axes...
Creating aligned images...
Measuring DNA axial extend...
DNA axial profile threshold 0: 3540.1683800070896
DNA axial profile threshold 1: 3548.702587734846
Measuring DNA lateral extend...
DNA lateral profile threshold 5877.7828947368425
DNA Otsu threshold: 3688.0
Remove small regions...
Spindle threshold: NaN
Computing mask...
Computing mask...
Creating projection of spindle mask along spindle axis...
Version: Spindle Morphometry Version: 0.7.1
DNA_Initial_Threshold: 4176.0
DNA_Volume_Threshold: 3688.0
DNA_Width_um: 3.5
DNA_Length_um: 12.0
DNA_Volume_um3: 509.171875
DNA_Normalised_Central_Intensity: 0.960589819680423
Spindle_Pole_Refinement_Distance_PoleA_um: 2.704163456597992
Spindle_Pole_Refinement_Distance_PoleB_um: 1.9685019685029528
Spindle_Length_um: 15.035374953754895
Spindle_Intensity_Threshold: NaN
Spindle_Volume_um3: 0.0
Spindle_Width_Min_um: 0.0
Spindle_Width_Max_um: 0.0
Dna_Center_To_Spindle_Center_Distance_um: 8.311325104939645
Spindle_Axis_To_Coverslip_Plane_Angle_Degrees: 23.356530008681304
Spindle_Tubulin_CoV: NaN
Spindle_Tubulin_Sum: NaN
Analysis finished.
```

**Comment by tischi** [comment]
This one works for me: `20200826_HeLa309_TubGFP_SiRDNA__PFAGA_NoMounting_005-1.tif`.
I uploaded again a new version. Could you please update Fiji and try again?

**Comment by TobiasKletter** [comment]
That solved it, thanks!
