### ISSUE TITLE
Various exceptions

### ISSUE THREAD

**Issue by TobiasKletter** [tischi/spindle3d#6]
Many images are throwing this exception (no further details...):

`java.lang.ArrayIndexOutOfBoundsException`

Sample:
https://www.dropbox.com/s/r0qj69st82gkh88/20200821_R1E309_EB1tdTomato_lipo075_01_028-Stack.tif?dl=0 

Others are throwing this one:
```
## Spindle Morphometry Measurement
Processing file 20200821_R1E309_EB1tdTomato_lipo075_01_050-Stack.tif
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Create isotropic images...
DNA initial threshold: 635.0
Remove small regions...
Determining DNA axes...
Creating aligned images...
Measuring DNA axial extend...
DNA axial profile threshold 0: 851.1481744062389
DNA axial profile threshold 1: 805.5072669266218
Measuring DNA lateral extend...
DNA lateral profile threshold 1095.90625
DNA Otsu threshold: 337.0
Remove small regions...
Spindle threshold: NaN
Computing mask...
[DEBUG] Spindle_length: 19.25
[DEBUG] Refined Spindle_length: 19.967160539245434
Computing mask...
Creating projection of spindle mask along spindle axis...
Version: Spindle Morphometry Version: 0.7.0
DNA_Initial_Threshold: 635.0
DNA_Volume_Threshold: 337.0
DNA_Width_um: 3.25
DNA_Length_um: 14.5
DNA_Volume_um3: 17700.078125
DNA_Normalised_Central_Intensity: 0.755453749565259
Spindle_Pole_Refinement_Distance_PoleA_um: 2.8722813232690143
Spindle_Pole_Refinement_Distance_PoleB_um: 2.5248762345905194
Spindle_Length_um: 19.967160539245434
Spindle_Intensity_Threshold: NaN
Spindle_Volume_um3: 0.0
Spindle_Width_Min_um: 0.0
Spindle_Width_Max_um: 0.0
Dna_Center_To_Spindle_Center_Distance_um: 10.126543092289689
Spindle_Axis_To_Coverslip_Plane_Angle_Degrees: 23.518192502231457
Spindle_Tubulin_CoV: NaN
Spindle_Tubulin_Sum: NaN
Analysis finished.
[ERROR] Module threw error
java.lang.NoSuchMethodError: de.embl.cba.morphometry.Utils.asRoundedLongs([D)[J
	at de.embl.cba.spindle3d.Spindle3DMorphometry.drawPoint(Spindle3DMorphometry.java:1664)
	at de.embl.cba.spindle3d.Spindle3DMorphometry.createInterestPointImage(Spindle3DMorphometry.java:1439)
	at de.embl.cba.spindle3d.Spindle3DMorphometry.createOutputImage(Spindle3DMorphometry.java:1523)
	at de.embl.cba.spindle3d.Spindle3DAdvancedCommand.processFile(Spindle3DAdvancedCommand.java:171)
	at de.embl.cba.spindle3d.Spindle3DAdvancedCommand.run(Spindle3DAdvancedCommand.java:107)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Error during module execution
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: de.embl.cba.morphometry.Utils.asRoundedLongs([D)[J
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.scijava.batch.ModuleBatchProcessor.processFile(ModuleBatchProcessor.java:141)
	at org.scijava.batch.ModuleBatchProcessor.run(ModuleBatchProcessor.java:118)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: de.embl.cba.morphometry.Utils.asRoundedLongs([D)[J
	at de.embl.cba.spindle3d.Spindle3DMorphometry.drawPoint(Spindle3DMorphometry.java:1664)
	at de.embl.cba.spindle3d.Spindle3DMorphometry.createInterestPointImage(Spindle3DMorphometry.java:1439)
	at de.embl.cba.spindle3d.Spindle3DMorphometry.createOutputImage(Spindle3DMorphometry.java:1523)
	at de.embl.cba.spindle3d.Spindle3DAdvancedCommand.processFile(Spindle3DAdvancedCommand.java:171)
	at de.embl.cba.spindle3d.Spindle3DAdvancedCommand.run(Spindle3DAdvancedCommand.java:107)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	... 8 more
```

https://www.dropbox.com/s/e2ky49csyyg0f1u/20200821_R1E309_EB1tdTomato_lipo075_01_050-Stack.tif?dl=0

**Comment by tischi** [comment]
@TobiasKletter 

Also here, the Otsu threshold is too low:
```
DNA lateral profile threshold 1095.90625
DNA Otsu threshold: 337.0
```

I hope that these errors are fixed by the fix in https://github.com/tischi/spindle3d/issues/5
Could you please check whether this true and then close the issue?

**Comment by TobiasKletter** [comment]
For both the above samples, the analysis seems to be working fine now (the results in the log seem meaningful) but there are new messages (the last one is entirely new), and again the result table + images are not saved. 

I get the feeling that I might need to (re)install something here?

```
## Spindle Morphometry Measurement
Processing file 20200821_R1E309_EB1tdTomato_lipo075_01_028-Stack.tif
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Create isotropic images...
DNA initial threshold: 357.5
Remove small regions...
Determining DNA axes...
Creating aligned images...
Measuring DNA axial extend...
DNA axial profile threshold 0: 574.7277561148529
DNA axial profile threshold 1: 575.2967032967033
Measuring DNA lateral extend...
DNA lateral profile threshold 714.2291666666666
DNA Otsu threshold: 637.0
Remove small regions...
Spindle threshold: 1278.1588352084714
Computing mask...
Spindle max derivative plus offset -5.0
Spindle max derivative minus offset 3.0
[DEBUG] Spindle_length: 8.0
[DEBUG] Refined Spindle_length: 7.949056547792323
Computing mask...
Creating projection of spindle mask along spindle axis...
Version: Spindle Morphometry Version: 0.7.0
DNA_Initial_Threshold: 357.5
DNA_Volume_Threshold: 637.0
DNA_Width_um: 9.5
DNA_Length_um: 3.5
DNA_Volume_um3: 253.3125
DNA_Normalised_Central_Intensity: 1.0
Spindle_Pole_Refinement_Distance_PoleA_um: 1.920286436967152
Spindle_Pole_Refinement_Distance_PoleB_um: 1.6583123951777
Spindle_Length_um: 7.949056547792323
Spindle_Intensity_Threshold: 1278.1588352084714
Spindle_Volume_um3: 272.203125
Spindle_Width_Min_um: 6.25
Spindle_Width_Max_um: 12.0
Dna_Center_To_Spindle_Center_Distance_um: 1.2930100540985752
Spindle_Axis_To_Coverslip_Plane_Angle_Degrees: 65.79130851591799
Spindle_Tubulin_CoV: 0.7445859198904793
Spindle_Tubulin_Sum: 6191574.931833219
Analysis finished.
[ERROR] Module threw error
java.lang.NoSuchMethodError: de.embl.cba.morphometry.Utils.asRoundedLongs([D)[J
	at de.embl.cba.spindle3d.Spindle3DMorphometry.drawPoint(Spindle3DMorphometry.java:1665)
	at de.embl.cba.spindle3d.Spindle3DMorphometry.createInterestPointImage(Spindle3DMorphometry.java:1440)
	at de.embl.cba.spindle3d.Spindle3DMorphometry.createOutputImage(Spindle3DMorphometry.java:1524)
	at de.embl.cba.spindle3d.Spindle3DAdvancedCommand.processFile(Spindle3DAdvancedCommand.java:171)
	at de.embl.cba.spindle3d.Spindle3DAdvancedCommand.run(Spindle3DAdvancedCommand.java:107)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

## Spindle Morphometry Settings
workingVoxelSize: 0.25
dnaThresholdResolution: 1.5
dnaThresholdFactor: 0.5
spindleDerivativeDelta: 1.0
minimalDynamicRange: 7
minimalDnaFragmentsVolume: 5.0
maxCentralObjectRegionsDistance: 7.0
erosionOfDnaMaskInCalibratedUnits: 1.0

## Spindle Morphometry Measurement
Processing file 20200821_R1E309_EB1tdTomato_lipo075_01_050-Stack.tif
Reading IFDs
Populating metadata
Checking comment style
Populating OME metadata
Create isotropic images...
DNA initial threshold: 644.5
Remove small regions...
Determining DNA axes...
Creating aligned images...
Measuring DNA axial extend...
DNA axial threshold 0: 838.3117679866147
DNA axial threshold 1: 785.0217512548801
Measuring DNA lateral extend...
Remove small regions...
Spindle threshold: 1092.692074847399
Computing mask...
Computing mask...
Creating projection of spindle mask along spindle axis...
Version: Spindle Morphometry Version: 0.5.9
DNA_Initial_Threshold: 644.5
DNA_Volume_Threshold: 1128.5416666666667
DNA_Width_um: 3.25
DNA_Length_um: 14.5
DNA_Volume_um3: 152.03125
DNA_Normalised_Central_Intensity: 0.7815600420585177
Spindle_Pole_Refinement_Distance_PoleA_um: 1.2747548783981961
Spindle_Pole_Refinement_Distance_PoleB_um: 0.9354143466934853
Spindle_Length_um: 15.878444508200417
Spindle_Intensity_Threshold: 1092.692074847399
Spindle_Volume_um3: 1126.546875
Spindle_Width_Min_um: 10.5
Spindle_Width_Max_um: 14.25
Dna_Center_To_Spindle_Center_Distance_um: 0.46770717334674267
Spindle_Axis_To_Coverslip_Plane_Angle_Degrees: 64.04119744417116
Spindle_Tubulin_CoV: 0.8455601833197041
Spindle_Tubulin_Sum: 3.1401849095577374E7
Analysis finished.
[ERROR] Module threw exception
java.lang.ClassCastException: net.imglib2.type.logic.BitType cannot be cast to net.imglib2.type.numeric.integer.GenericShortType
	at net.imglib2.type.numeric.integer.GenericShortType.set(GenericShortType.java:53)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.lambda$getSlice$1(ImageJVirtualStack.java:171)
	at net.imglib2.display.projector.IterableIntervalProjector2D.map(IterableIntervalProjector2D.java:151)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.project(ImageJVirtualStack.java:181)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getSlice(ImageJVirtualStack.java:171)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getPixelsZeroBasedIndex(ImageJVirtualStack.java:198)
	at net.imglib2.img.display.imagej.AbstractVirtualStack.getPixels(AbstractVirtualStack.java:102)
	at net.imglib2.img.display.imagej.AbstractVirtualStack.getProcessor(AbstractVirtualStack.java:163)
	at ij.ImagePlus.setSlice(ImagePlus.java:1858)
	at ij.ImagePlus.setPosition(ImagePlus.java:1744)
	at ij.ImagePlus.setC(ImagePlus.java:1761)
	at de.embl.cba.morphometry.spindle.SpindleMorphometry.createOutputImage(SpindleMorphometry.java:1592)
	at de.embl.cba.morphometry.spindle.SpindleMorphometryCommand.processFile(SpindleMorphometryCommand.java:161)
	at de.embl.cba.morphometry.spindle.SpindleMorphometryCommand.run(SpindleMorphometryCommand.java:92)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tischi** [comment]
Hmm, that's weird. Can you download a fresh Fiji and then add the Spindle3D Update site?

**Comment by TobiasKletter** [comment]
Solved!
